// <auto-generated />
namespace AldursLab.WurmAssistantWebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModifyWurmAssistant3PackagesAndAddLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyWurmAssistant3PackagesAndAddLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201509102107262_ModifyWurmAssistant3PackagesAndAddLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
